logging:
    logdir: log
    level:
        root: info
        com.feng: debug
        org.springframework.security: warn
spring:
    profiles:
        active: dev
    application:
        name: app
    jackson:
        serialization.write_dates_as_timestamps: false
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
server:
    port: 80
